### PR TITLE
config: add pipewire module to default and example configuration

### PR DESCRIPTION
**Pull request by robert-scheck**

### CODE REVIEW

**Comment by cspiel1** [comment]
Looks good to me. We should merge this after https://github.com/baresip/baresip/pull/2439

**Comment by robert-scheck** [comment]
> Looks good to me. We should merge this after https://github.com/baresip/baresip/pull/2439

Would you like to see my pull request against your fork or against upstream baresip then?

**Comment by cspiel1** [comment]
I always think against upstream `main`. Oh, sorry I didn't saw the merge target is my fork. Yes I could add this to my branch. Thanks!

**Comment by cspiel1** [comment]
But please could you rebase your branch onto my `cspiel1:pipewire_module`?

**Comment by cspiel1** [comment]
I applied this to my branch manually. Thanks!
https://github.com/baresip/baresip/pull/2439/commits/646d1fc98a1e84a0a786f532f1ff2c82e38c97ba

**Pull request closed without merging**
